db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://ep-square-brook-adcxc4km-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
db.username=neondb_owner
db.password=npg_bQm3Tqs9iXOh

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true